spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sharing}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
  sql:
    init:
      data-locations: classpath:sql/data.sql
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create}

jwt:
  secret: ${JWT_SECRET:Vm1wS01HRXlUWGxXYmxKVFlXeGFUMVl3YUVOaU1WWnhVVzFHVDFadGVGaFhXSEJIWVZkRmVXVkZXbHBoYXpWRFZVWkZPVkJSUFQwPQ==}
  lifetime: ${JWT_LIFETIME:1} # In days